### ISSUE TITLE
How should modules using datacat be tested?

### ISSUE THREAD

**Issue by nhinds** [richardc/puppet-datacat#28]
I'm trying to write tests via `rspec-puppet` for a new module using `datacat`, but since `datacat_collector` doesn't actually evaluate the template until the catalog starts to be applied I can't find a way to assert on my template applying correctly. The file always ends up with the content "To be replaced by datacat_collector[...]".

I'd prefer not to go to a system test with beaker or rspec-system for testing an ERB.

**Comment by richardc** [comment]
Sorry, you're out of luck.  The data is only merged and formatted at catlog apply time, and rspec-puppet only gives you a compiled catalog to inspect.

The best you can do is to make a test class with static data that you expect your datacat_fragment chunks will merge down to, feed that to your template, and just check that at least that part of the chain works.

**Comment by nhinds** [comment]
Fair enough.

In case other people are curious, I did find a way of testing it without resorting to static data, but I'm not convinced it's any better than just running system tests:

```
let(:monkeyed_catalog) do
  catalogue.to_ral.tap do |ral|
    ral.resource('datacat_collector', '/my/datacat/path').provider.exists?
  end
end

subject(:zone_content) { monkeyed_catalog.resource('file', '/my/datacat/path').property('content').actual_content }
```

**Comment by nhinds** [comment]
Sorry, I haven't had a chance to clean this up for the readme. I'm a little worried that the technique only works for specific versions of Puppet, since it does use two internal features (`to_ral` and the `.actual_content` property of the `file` resource)
