### ISSUE TITLE
librarian-puppet issue 

### ISSUE THREAD

**Issue by rhoml** [richardc/puppet-datacat#32]
We are using librarian-puppet and there is some problem with the dependencies of the module

```
Could not resolve the dependencies.
```

**Comment by richardc** [comment]
Could you include some steps to replicate, as far as I can see the dependencies (none) are correctly specified:  https://github.com/richardc/puppet-datacat/blob/0.6.2/metadata.json#L11

**Comment by richardc** [comment]
Could not reproduce in isolation:

```shell
$ cat Puppetfile
forge "https://forgeapi.puppetlabs.com"

mod "richardc-datacat"

$ librarian-puppet install
$ ls modules/datacat/
Changes         NOTES.md        Rakefile        checksums.json  manifests       spec
Gemfile         README.md       TODO.md         lib             metadata.json
```

**Comment by rhoml** [comment]
Apparently it is related to other modules. Sorry.
