### ISSUE TITLE
puppet version requirements

### ISSUE THREAD

**Issue by tobiasschaber** [richardc/puppet-datacat#35]
Hi!

A few days ago I used the https://github.com/elastic/puppet-elasticsearch module which depends on your datacat module. I tried it on ubuntu 14.04 with puppet 3.4.3. The installation failed, because my puppet version was to old (see https://github.com/elastic/puppet-elasticsearch). 

Would it be a solution to add the puppet minimum version to your metadata fie?

Thanks and kind regards,

Tobias

**Comment by richardc** [comment]
But this code should work with 3.4.3.  It is tested against it: https://github.com/richardc/puppet-datacat/blob/master/.travis.yml#L12

Can you show the error you get?
