### ISSUE TITLE
Can't use global variables and scope inside datacat templates

### ISSUE THREAD

**Issue by Andor** [richardc/puppet-datacat#36]
I was trying to add into template for datacat:
```
# puppet module <%= @modulename %>
# puppet resource/class title <%= scope.lookupvar('title') %>
```
I get empty string (undef, obviously)
`@classname.inspect` returns `nil`
```
# puppet class <%= scope['classname'] %>
```
I get error `Could not evaluate: Could not find value for 'scope'`

**Comment by richardc** [comment]
Yes, this is covered by the caveat in the README about where the erb is evaluated.  There is no `scope` in that calling scope.
