### ISSUE TITLE
Concat::Fragment's content is not updated by datacat

### ISSUE THREAD

**Issue by hansmi** [richardc/puppet-datacat#37]
I have a configuration file for OpenSSH written using the `puppetlabs/concat` module. One of the fragments is supposed to comprise a couple of values collected using `datacat`. To that end I set `target_resource` to `Concat::Fragment[…]` and `target_field` to `content`. Unfortunately the fragment ends up using its default content in the final file (`# datacat` in the code given below), not the output from the datacat template.

One workaround is to let datacat write the template output to a file and use that as `concat::fragment`'s `source`.

Is it possible that datacat is incompatible with `puppetlabs/concat`'s internal structure?
# Example code

Tested with Puppet 4.5.3:

```
::concat { 'test_config':
  ensure         => present,
  path           => '/tmp/test.cfg',
  ensure_newline => true,
}

::concat::fragment { 'test_config_header':
  target  => 'test_config',
  order   => '1',
  content => "# header\n",
}

::concat::fragment { 'test_config_footer':
  target  => 'test_config',
  order   => '3',
  content => "# footer\n",
}

datacat_collector { 'test_config_extra':
  target_resource => Concat::Fragment[test_config_datacat],
  target_field    => 'content',
  template_body   => @("EOF"/),
  <% @data.keys.sort.each do |name| -%>
  <%= name %> <%= @data[name].sort.join(',') -%>
  <% end -%>
  | EOF
} ->
::concat::fragment { 'test_config_datacat':
  target  => 'test_config',
  order   => '2',
  content => "# datacat\n",
}

datacat_fragment { "test_config_extra_foo":
  target => 'test_config_extra',
  data => {
    'foo' => ['bar'],
  },
}
```
# Expected result

```
# header
foo bar
# footer
```
# Actual result

```
# header
# datacat
# footer
```

**Comment by richardc** [comment]
The issue here is that you cannot effectively point a datacat_collector at a defined type; only native types work, due to the way the resources are handled in the catalog. 

 If you're using a modern version of concat you might try targeting the native concat_fragment type that it wraps - https://github.com/puppetlabs/puppetlabs-concat/blob/2.2.0/manifests/fragment.pp#L49-L55 or carry on with your existing workaround of using an intermediate file.

**Comment by hansmi** [comment]
> […] you might try targeting the native concat_fragment type that it wraps […]

Thank you for the hint, that indeed works too. With the example given in the original comment the changes needed are as follows:

```
[…]
datacat_collector { 'test_config_extra':
  target_resource => Concat_fragment[test_config_datacat],
  […]
```
