### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by fvanboven** [richardc/puppet-datacat#38]
Hi, could you release a new version to the Forge? Old one is over a year old, would be nice if we can get the latest tweaks

**Comment by richardc** [comment]
There are no tweaks to release.   Most recent forge release is 0.6.2.

This is the comparison between master and 0.6.2:  https://github.com/richardc/puppet-datacat/compare/0.6.2...master

**Comment by fvanboven** [comment]
Thanks for the clarification. We're currently locked to a specific commit from after 0.6.2. But indeed, there are no real code changes in there.

Apologies for the distraction!
