### ISSUE TITLE
Unclear how to use datacat_collector to set a resource field value

### ISSUE THREAD

**Issue by akomakom** [richardc/puppet-datacat#42]
I'm trying to collect strings across modules to build a single delimited string parameter that needs to be passed to a puppet class.  I've tried a dozen combinations and got nowhere.

### Attempt 1:
```
class {'jenkins::slave':
   labels => 'a list of labels',  # this works.
}

datacat_collector{"machine_capabilities":
    template_body => strip("test321 <%=@data['labels'].sort.join(' ') %>"),
    target_resource => Class['jenkins::slave'],
    target_field => 'labels',
}

datacat_fragment{"machine_capabilities_awscli":
  target => "machine_capabilities",
  data => {labels => ['awscli']},
}
```

**Result:** 
* If I leave the labels parameter set in jenkins::slave, I get the hardcoded value
* If I remove the labels parameter, I get nothing (undef), not even "test321"

### Attempt 2:
(This is not what I want, but I'm checking whether I can set fields on built-in types)

```
file{'/tmp/test_datacat':
  ensure => file,
}
datacat_collector{"machine_capabilities":
    template_body => strip("test321 <%=@data['labels'].sort.join(' ') %>"),
    target_resource => File['/tmp/test_datacat'],
    target_field => 'content',
}
datacat_fragment{"machine_capabilities_awscli":
  target => "machine_capabilities",
  data => {labels => ['awscli']},
}
```

**Result:** Nothing in file.  If I add content=> "value", I get the hardcoded string.

The docs seem to suggest that the above should work. What am I doing wrong?

Puppet 5, datacat 0.6.2

**Comment by richardc** [comment]
Using datacat with class parameters isn't going to work at all I'm afraid - they're evaluated at a much earlier phase, and aren't really resources in a catalog.

**Comment by richardc** [comment]
As to why second version isn't working - I'm not sure;   the version that's tested as part of CI is working under puppet 5.3: https://travis-ci.org/richardc/puppet-datacat/jobs/322333019#L1411 https://github.com/richardc/puppet-datacat/blob/master/test/integration/default/site.pp

**Comment by richardc** [comment]
Ah; I think you're missing the explicit before.  https://github.com/richardc/puppet-datacat/blob/master/manifests/init.pp#L92

**Comment by akomakom** [comment]
@richardc thank you, I confirmed both cases.  It may be a good idea to update the examples with an explicit **before** (or make that implied from target, if that's possible).  As for my use cases

**Comment by akomakom** [comment]
@richardc thank you, I confirmed both cases.  It may be a good idea to update the examples with an explicit **before** (or make that implied from target, if that's possible).  And a caveat about setting class parameters might be good too.

As for my use case with class, I can work around it by using a file as a target, although that's less convenient.

**Comment by maggu** [comment]
I second that it would be quite useful if the documentation were more clear on what can be targeted and what can not. It would appear that I can't target defined resource types either?

For example, this works fine to get tempfiles with correct comma-separated user lists:

```
  datacat_collector { "group ${title}":
    template_body   => '<%= @data["users"].sort.join(", ") %>',
    target_resource => File[$title],
    target_field    => 'content',
    before          => File[$title],
  }

  file { $title:
    path    => "/tmp/${title}",
    content => "To be replaced by collector",
  }
```

I want to do a bit more with them though. However, wrapping it like below apparently does not work? (Unless, of course, I managed to screw it up somehow, but then I don't quite see how at the moment.)

I get the placeholder string instead.

```
  define icinga::role (
    String $users,
  ) {
    file { $title:
      path    => "/tmp/${title}",
      content => $users,
    }
  }
```
```
  datacat_collector { "group ${title}":
    template_body   => '<%= @data["users"].sort.join(", ") %>',
    target_resource => Icinga::Role[$title],
    target_field    => 'users',
    before          => Icinga::Role[$title],
  }

  icinga::role { $title:
    users => "To be replaced by collector",
  }
```

**Comment by richardc** [comment]
>  I can't target defined resource types either?

I'm afraid not. 

The parameters of a defined resource are passed onto concrete resources during catalog compilation; they're not meaningfully targetable at run-time, which is when datacat operates.
